// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-5OeUgzyARgCpqy-6gRZxO0qcvqu_uIs',
    appId: '1:863606792588:web:4ce7540814e51632f076a9',
    messagingSenderId: '863606792588',
    projectId: 'time-capsule-4612b',
    authDomain: 'time-capsule-4612b.firebaseapp.com',
    storageBucket: 'time-capsule-4612b.firebasestorage.app',
    measurementId: 'G-4QQT3JVXC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPd1-F8LEX2iH_meaXSalKol6LZUWBiAE',
    appId: '1:863606792588:android:9e48d03eb7934881f076a9',
    messagingSenderId: '863606792588',
    projectId: 'time-capsule-4612b',
    storageBucket: 'time-capsule-4612b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8m9oR3_yzdCRQlyESIitqfTxetnkJC8g',
    appId: '1:863606792588:ios:9f6bbf127a569d41f076a9',
    messagingSenderId: '863606792588',
    projectId: 'time-capsule-4612b',
    storageBucket: 'time-capsule-4612b.firebasestorage.app',
    iosBundleId: 'in.khoinchha.app.kohinchha',
  );
}
